### ISSUE TITLE
Memory intensive for loading all icons at once and initializing on multiple inputs (pagination needed)

### ISSUE THREAD

**Issue by friday-code** [dogukanakkaya/iconpicker#1]
The library is extremely memory intensive especially when i ported it for font awesome 6 (self built json 😅) and when used on multiple input fields at the same time on the same page. it crashes when you try to open the second input due to high resources. Is there a way to implement pagination into it where it loads only 20 or 30 icons along with paginations buttons instead of displaying all 3000+ icons at once when i only need to pick one. A similar feature is seen on [Bootstrap Iconpicker Library](https://github.com/victor-valencia/bootstrap-iconpicker) 
<img width="237" alt="Screenshot 2023-08-12 at 11 51 55 AM" src="https://github.com/dogukanakkaya/iconpicker/assets/90507683/b5b154a4-2758-49a5-9a1a-d46766ed4c12">

**Comment by dogukanakkaya** [comment]
This is not maintained to be honest. It's been more than 2 years since I created this package and now it's a very amateur one. I see that the code and the repository is terrible at the moment when I look, this was a very quick need for me back then, written in haste.

I'll not bother to touch or rewrite this. If you can, please use another package that meet your needs, sorry. You can also fork and change it to your needs if you like.
